### PR TITLE
Updated to Swift 5.1 and Xcode 11

### PR DESCRIPTION
**Pull request by RahulBhalley**
I have updated the playgrounds to Swift 5.1 and Xcode 11. Note that *all playgrounds now work correctly except two* which I wasn't able to update, unfortunately. These are FFT and SmoothWalker. 

Please accept the pull request. 🙂

### CODE REVIEW

**Comment by hyperjeff** [comment]
Sorry for taking so long to get to this and thank you for the PR! I'll get to the other two when I get a chance.

**Comment by bradhowes** [comment]
Nice work @rahulbhalley ! I added fixes for FFT and SmoothWalker in my own pull request #4

**Comment by RahulBhalley** [comment]
Man do you even have any plans to merge it or not?

**Comment by hyperjeff** [comment]
I am terrible at githubbing, clearly. I so rarely come to the website and I miss the activity. Apologies to you both.

**Pull request closed without merging**
